# Classes

In Python, "everything" is an object, including ints, strs, floats, lists, dicts, etc. Every object has an identity and a type that may be accessed with the functions `id` and `type` respectively.

*Classes* allow us to define new types. This is very useful when we cannot find any appropriate existing type. In [another notebook](http://localhost:8889/notebooks/data_types.ipynb), we looked at different ways to represent a set of countries. We saw, e.g., that a country could be represented as a tuple:

In [9]:
# ints are objects too

def fibonacci(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return b

print([fibonacci(i) for i in range(20)])
print()
print(f'fibonacci(1000) = {fibonacci(1000)}')

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765]

fibonacci(1000) = 70330367711422815821835254877183549770181269836358732742604905087154537118196933579742249494562611733487750449241765991088186363265450223647106012053374121273867339111198139373125598767690091902245245323403501


In [13]:
a = 42
print(id(a))
print(type(a))
print(id(42))

4372665392
<class 'int'>
4372665392


In [14]:
france = ("France", "Paris", 66.99)

print(f'The capital of {france[0]} is {france[1]}. ' 
      f"The contry's population is {france[2]} million.")

The capital of France is Paris. The contry's population is 66.99 million.


Using such a representation can be a shorthand to solve an imminent problem, but can quickly become impractical. We have to remember the position of each of the items that make up the country tuple. Also, if we wanted to mutate a country (e.g., update the population), we would need a mutable representation of a country, such as a list. However, if a country is represented as list, we may be allowing for too much mutability. What if we wanted country name and capital to be immutable, and only the population could be altered? 

## First step

Let's take a first stab at defining a `Country` class.

In [15]:
class Country(object):
    """A class that represents countries"""
    
    def __init__(self, name, capital, population):
        self.name = name
        self.capital = capital
        self.population = population

In [16]:
france = Country("France", "Paris", 66.99)

print(f'The capital of {france.name} is {france.capital}. ' 
      f"The country's population is {france.population} million.")

The capital of France is Paris. The country's population is 66.99 million.


This representation of Country makes the code more readable!

Let's dissect the definition of the `Country` class:

1. `class Country(object)`:  
`class` is a keyword used when defining classes. `Country` is the class name. The convention is to use "camel case" for class names. `object` is the class's *superclass*. Ignore the superclass for now.
2. `"""A class that represents countries"""`:  
is an optional *doc string*. 
3. The `__init__` function:  
This function always has this particular name. The first argument `self` refers to the object that this function is applied to and must always be present. When `Country("France", "Paris", 66.99)` is called, an object of type `Country` is created, after which `__init__` is called with the new objec assigned to `self`, `"Fance"` assigned to `name`, `"Paris"` assigned to `capital`, and `66.99` assigned to `population`.
4. The body of the `__init__` function saves the values passed to the function arguments as *object attributes*.

**Note:** We can break calling `ireland = Country("Ireland", "Dublin", 4.88)` into several steps"

In [ ]:
ireland = Country.__new__(Country)
Country.__init__(ireland, "Ireland", "Dublin", 4.88)
ireland

## Attribute access

The attributes of any `Country` object are accessible from anywhere. In Python there is no enforcement of *private* attributes. However, if an attribute name begins with an underscore character (`_`), then this is by convention an indication that the attribute should not be referenced outside the class definition.

Let's make all the object attributes "private" and add *getters* so we can access the these attributes without breaking any convention. Also add a *setter* to modify the population.

In [17]:
class Country(object):
    """A class that represents countries"""
    def __init__(self, name, capital, population):
        self._name = name
        self._capital = capital
        self._population = population

    def name(self):
        return self._name

    def capital(self):
        return self._capital

    def population(self):
        return self._population

    def set_population(self, population):
        self._population = population


france = Country("France", "Paris", 66.99)

france.set_population(67.0)

print(f'The capital of {france.name()} is {france.capital()}. '
      f"The contry's population is {france.population()} million.")

The capital of France is Paris. The contry's population is 67.0 million.


Notice that all the functions have `self` as the first argument. Calling `france.name()` is equivalent to calling...

In [18]:
Country.name(france)

'France'

... and same holds for the other functions. The functions that are defined inside a class definition and have `self` as the first argument are often referred to as *methods*.

**Note:** The first argument of a method doesn't *have* to be called `self`. It's called `self` by convention and, unless you want to confuse the readers of your code, you should use the same name.

## Inherited attributes

We've seen that the builtin function `dir()` can be called to return a list of all defined variables. Similarly, this function can also be used to get a list of all attributes of a class

In [19]:
dir(Country)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'capital',
 'name',
 'population',
 'set_population']

The attributes we've defined are at the end of the list. Notice that the private attributes `_name`, `_capital`, and `_population` are not in this list. 

The remaining attributes are inherited from `object`, which is `Country`' s superclass. Because they start and end in **d**ouble **under**scores, they are often referred to as *dunder methods*.

Normally, the dunder methods are never called directly. They are only called by certain builtin functions. For example, `__str__` is called when calling `str` on an object. It's also called when printing an object. Similarly, `__repr__` is called when `repr` is called on the object. This function should return an expression that, when evaluated, is equal to the object. And what does "equal" mean in this context? That's defined by the `__eq__` method.

By default `str` doesn't return anything that's intelligible. We can change that by *overriding* the `__str__` method.

In [20]:
print(france)
str(france)

'<__main__.Country object at 0x1094c03d0>'

Same goes for `repr`:

In [22]:
repr(france)

'<__main__.Country object at 0x1094c03d0>'

Two distinct objects are never equal unless `__eq__` is overridden.

In [ ]:
france == Country("France", "Paris", 66.99)

In [24]:
class Country(object):
    """A class that represents countries"""
    def __init__(self, name, capital, population):
        self._name = name
        self._capital = capital
        self._population = population

    def name(self):
        return self._name

    def capital(self):
        return self._capital

    def population(self):
        return self._population

    def set_population(self, population):
        self._population = population

    def __str__(self):
        return f'Country({self._name}, {self._capital}, {self._population})'

    def __repr__(self):
        return f'Country({repr(self._name)}, {repr(self._capital)}, {repr(self._population)})'

    def __eq__(self, other):
        if not isinstance(other, Country):
            return False
        return self._name == other._name\
           and self._capital == other._capital\
           and self._population == other._population

In [25]:
france = Country("France", "Paris", 66.99)
print(france)
str(france)

Country(France, Paris, 66.99)


'Country(France, Paris, 66.99)'

In [26]:
repr(france)

"Country('France', 'Paris', 66.99)"

In [27]:
france2 = eval(repr(france))

In [28]:
france == france2

True

In [29]:
id(france) == id(france2)

False

In [30]:
france != 42

True

In [33]:
france.set_population(100.0)
france == france2
print(france, france2)

Country(France, Paris, 100.0) Country(France, Paris, 66.99)


In [39]:
a = [[0] * 3 for _ in range(2)]
id(a[0]) == id(a[1])
# a[0][0] = 1
# a

False

## Exercise 1

Define a `Temperature` class. One should be able to instantiate a temperature object in the following way:

```Python
temp = Temperature(25.5, scale='Celsius')
```

This should assign a Temperature object to `temp` that represents a temperature of 25.5 ℃. If the argument `scale` is omitted, it defaults to `"Celsius"`. The scale can only be `"Celsius"`, `"Kelvin"` or `"Fahrenheit"`. If any other value is passed, an exception should be raised with an informative message.


In [34]:
class Temperature(object):

    absolute_zero = 273.15

    def __init__(self, temp, scale="Celsius"):

        if scale not in ("Kelvin", "Celsius", "Fahrenheit"):
            raise ValueError(f"Unknown temperature scale: {scale}")

        self._temperature = temp if scale == "Kelvin"\
                else (temp + Temperature.absolute_zero) if scale == "Celsius"\
                else ((temp - 32) * 5 / 9 + Temperature.absolute_zero) if scale == "Fahrenheit"\
                else None
        if self._temperature < 0:
            self._temperature = 0
            raise ValueError("Temperature cannot be below absolute zero.")

    def temperature(self, scale="Celsius"):
        absolute_zero = Temperature.absolute_zero
        if scale == "Kelvin":
            return round(self._temperature, 2)
        if scale == "Celsius":
            return round(self._temperature - absolute_zero, 2)
        if scale == "Fahrenheit":
            return round((self._temperature - absolute_zero) * 9 / 5 + 32, 2)
        raise ValueError(f"Unknown temperature scale: {scale}")

    def __eq__(self, other):
        return isinstance(other, Temperature)and\
               abs(self._temperature - other._temperature) < 1e-2

    def __str__(self):
        return f'Temperature({round(self._temperature, 2)}, "Kelvin")'

    __repr__ = __str__

    def __hash__(self):
        return hash(self._temperature)

    def __lt__(self, other):
        return isinstance(other, Temperature) and\
               self._temperature < other._temperature
    
    def __add__(self, other):
        if not isinstance(other, Temperature): 
            raise TypeError()
        return Temperature(self._temperature + other._temperature, "Kelvin")
    
#     __iadd__ = __add__

Let the class have a private `_temperature` attribute and define a getter:

```Python
   def temperature(self, scale="Celcius"):
        pass
```

In [15]:
temp_today = Temperature(70.0, scale="Fahrenheit")
temp_today.temperature("Celsius")
str(temp_today)

'Temperature(294.26, "Kelvin")'

In [16]:
Temperature.absolute_zero

273.15

In [17]:
repr(temp_today)

'Temperature(294.26, "Kelvin")'

In [18]:
eval(_)

Temperature(294.26, "Kelvin")

In [19]:
abs_zero = Temperature(0, "Kelvin")
print(f'abs_zero in Fahrenheit = {abs_zero.temperature("Fahrenheit")}')
print(f'abs_zero = {abs_zero}')

abs_zero in Fahrenheit = -459.67
abs_zero = Temperature(0, "Kelvin")


Let the `__init__` method check that the temperature is above absolute zero (-273.15 ℃) and raise a ValueError if it's not.

In [30]:
try:
    impossible_temp = Temperature(-300)
except ValueError as e:
    print(f"{e} Luckily we caught that one!")

Temperature cannot be below absolute zero. Luckily we caught that one!


Override the methods `__eq__`, `__hash__`, `__str__`, `__repr__`. Identify any other dunder methods which it makes sense to override, and override them too. Verify that you can make a set of Temperature objects.

In [35]:
s = {
    Temperature(22),
    Temperature(10),
    Temperature(20),
    Temperature(70, "Fahrenheit")
}

print(Temperature(10) in s)
temps = sorted(s)
print(temps)
print(min(s), max(s))
print((Temperature(75, "Fahrenheit") + Temperature(3, "Kelvin")).temperature("Fahrenheit"))

t0 = Temperature(0, "Celsius")
t0 += Temperature(10, "Kelvin")
print(f't0 = {t0}')
# print(sum(s, Temperature.absolute_zero))
sum?

True
[Temperature(283.15, "Kelvin"), Temperature(293.15, "Kelvin"), Temperature(294.26, "Kelvin"), Temperature(295.15, "Kelvin")]
Temperature(283.15, "Kelvin") Temperature(295.15, "Kelvin")
80.4
t0 = Temperature(283.15, "Kelvin")


## Exercise 2

Let's implement a heap. A heap is a *complete binary tree* such that the value of a parent is smaller (in case of a min heap) or greater (in case of a max heap) than or equal to the values of the children (if any). This assumes that the values of the nodes are comparable.

![Max Heap](https://upload.wikimedia.org/wikipedia/commons/3/38/Max-Heap.svg)

Heaps can be represented by lists. If one were to index the nodes starting starting with the root (index=0) and continuing downwards left to right, then each node will have an index that is $2x + 1$ if $x$ is the index of the parent and it's a left node, or $2x + 2$ if it's a right node.

![Heap as array](https://upload.wikimedia.org/wikipedia/commons/d/d2/Heap-as-array.svg)

In this exercise, we will implement a min heap.

In [1]:
# Example of a list representing a min heap
[1, 2, 3, 7, 6, 3, 4, 8]

[1, 2, 3, 7, 6, 3, 4, 8]

1. Define a class `Heap` with an `__init__` method that takes a list as argument.

In [45]:
class Heap(object):
    
    def __init__(self, lst):
        self._lst = lst[:]

In [36]:
# Your solution here
class Heap(object):
    pass

Add a function `heapify(lst)`, which, when called, returns a new list with the same elements as it's argument but such that the returned list satisfies the heap condition. Assume that the elements are comparable.

In [111]:
def heapify(lst):
    if not lst: return []
    res = lst[:]
    n = len(res)
    
    def sift_down_rec(i):
        lidx = 2 * i + 1
        ridx = lidx + 1
        if lidx >= n or\
           ridx >= n and res[i] <= res[lidx] or\
           res[i] <= res[lidx] and res[i] <= res[ridx]: 
            return
        if ridx >= n or res[lidx] <= res[ridx]:
            res[lidx], res[i] = res[i], res[lidx]
            sift_down_rec(lidx)
        else:
            res[ridx], res[i] = res[i], res[ridx]
            sift_down_rec(ridx)

    def sift_down_iter(i):
        while True:
            lidx = 2 * i + 1
            ridx = lidx + 1
            if lidx >= n or\
               ridx >= n and res[i] <= res[lidx] or\
               res[i] <= res[lidx] and res[i] <= res[ridx]: 
                break
            if ridx >= n or res[lidx] <= res[ridx]:
                res[lidx], res[i] = res[i], res[lidx]
                i = lidx
            else:
                res[ridx], res[i] = res[i], res[ridx]
                i = ridx
        
        
    for i in range((n - 2) // 2, -1, -1):
        sift_down_iter(i)
    return res
    

In [58]:
# Your solution here
def heapify(lst):
    pass

In [116]:
heap = heapify([7, 4, 7, 3, 2, 8, 1, 4, 3, 1])
heap

[1, 2, 1, 3, 4, 8, 7, 4, 3, 7]

Move `heapify` to the class `Heap` and call it in `__init__`. Rename it so it appears as private.

In [117]:
class Heap(object):
    
    def __init__(self, lst):
        self._lst = lst[:]
        self._heapify()
    

    def _heapify(self):
        if not self._lst: return
        n = len(self._lst)
        for i in range((n - 2) // 2, -1, -1):
            self._sift_down(i)
    
    def _sift_down(self, i):
        """assert(0 <= i < len(self._lst))"""
        n = len(self._lst)
        lidx = 2 * i + 1
        ridx = lidx + 1
        if lidx >= n or\
           ridx >= n and self._lst[i] <= self._lst[lidx] or\
           self._lst[i] <= self._lst[lidx] and self._lst[i] <= self._lst[ridx]: 
            pass
        elif ridx >= n or self._lst[lidx] <= self._lst[ridx]:
            self._lst[lidx], self._lst[i] = self._lst[i], self._lst[lidx]
            self._sift_down(lidx)
        else:
            self._lst[ridx], self._lst[i] = self._lst[i], self._lst[ridx]
            self._sift_down(ridx)


In [118]:
heap = Heap([3, 5, 2, 13, 2, 5, 3, 8, 7, 6, 6, 8])
heap._lst

[2, 3, 2, 7, 5, 5, 3, 8, 13, 6, 6, 8]

In [49]:
# Your solution here

class Heap(object):
    
    def __init__(self, lst):
        pass
    

    def _heapify(self):
        pass
    
    def _sift_down(self, i):
        pass

Add a method `is_empty(self)`, which should return `True` if the heap is empty, `False` otherwise.

In [46]:
def is_empty(self):
    return not self._lst

In [ ]:
# Your solution here
def is_empty(self):
    pass

Add a method `peek(self)`, which should return the item at the root of the heap. If the heap is empty, the method should raise a `StopIteration` exception.

In [47]:
def peek(self):
    if self._lst: return self.lst[0]
    raise StopIteration()

In [50]:
# Your solution here
def peek(self):
    pass

Add a method `pop(self)` which should return and remove the smallest item on the heap. If the heap is empty, it should raise a `StopIteration`.

In [1]:
def pop(self):
    if not self._lst:
        raise StopIteration()
    res = self._lst[0]
    self._lst[0] = self._lst.pop()
    self._sift_down(0)
    return res

In [2]:
# Your solution here
def pop(self):
    pass

Add a method `push(self, item)`, which should add `item` to the heap.

In [16]:
def push(self, item):
    self._lst.append(item)
    self._sift_up(len(self._lst) - 1)
    
def _sift_up(self, i):
    """assert(0 <= i <= len(self._lst))"""
    if i == 0: return
    j = (i - 1) // 2 # j is the index of the parent node
    if self._lst[i] < self._lst[j]:
        self._lst[i], self._lst[j] = self._lst[j], self._lst[i]
        self._sift_up(j)

In [17]:
# Your solution here
def push(self, item):
    pass

Update the class `Heap` with the methods defined above.

In [33]:
class Heap(object):
    
    def __init__(self, lst):
        self._lst = lst[:]
        self._heapify()

    def _heapify(self):
        if not self._lst: return
        n = len(self._lst)
        for i in range((n - 2) // 2, -1, -1):
            self._sift_down(i)
    
    def _sift_down(self, i):
        """assert(0 <= i < len(self._lst))"""
        n = len(self._lst)
        lidx = 2 * i + 1
        ridx = lidx + 1
        if lidx >= n or\
           ridx >= n and self._lst[i] <= self._lst[lidx] or\
           self._lst[i] <= self._lst[lidx] and self._lst[i] <= self._lst[ridx]: 
            return
        if ridx >= n or self._lst[lidx] <= self._lst[ridx]:
            self._lst[lidx], self._lst[i] = self._lst[i], self._lst[lidx]
            self._sift_down(lidx)
        else:
            self._lst[ridx], self._lst[i] = self._lst[i], self._lst[ridx]
            self._sift_down(ridx)

    def _sift_up(self, i):
        """assert(0 <= i <= len(self._lst))"""
        if i == 0: return
        j = (i - 1) // 2
        if self._lst[i] < self._lst[j]:
            self._lst[i], self._lst[j] = self._lst[j], self._lst[i]
            self._sift_up(j)

    def is_empty(self):
        return not self._lst
    
    def peek(self):
        if self._lst: return self.lst[0]
        raise StopIteration()
        
    def pop(self):
        if not self._lst:
            raise StopIteration()
        if len(self._lst) == 1:
            return self._lst.pop()
        res = self._lst[0]
        self._lst[0] = self._lst.pop()
        self._sift_down(0)
        return res
    
    def push(self, item):
        self._lst.append(item)
        self._sift_up(len(self._lst) - 1)


In [55]:
# Your solution here
class Heap(object):
    
    def __init__(self, lst):
        pass

    def _heapify(self):
        pass
    
    def _sift_down(self, i):
        pass

    def _sift_up(self, i):
        pass

    def is_empty(self):
        pass
    
    def peek(self):
        pass
    
    def pop(self):
        pass
    
    def push(self, item):
        pass



Which dunder methods does it make sense to add to `Heap`?

Compare the `Heap` class with the `heapq` module that comes with Python.

In [42]:
import heapq
heapq?

In [38]:
a = [8, 4, 3, 8, 9, 1, 2, 1, 9, 5, 2]
heapq.heapify(a)
a

[1, 1, 2, 4, 2, 3, 8, 8, 9, 5, 9]

In [39]:
print(heapq.heappop(a))
a

1


[1, 2, 2, 4, 5, 3, 8, 8, 9, 9]

In [40]:
heapq.heappush(a, 6)

In [41]:
a

[1, 2, 2, 4, 5, 3, 8, 8, 9, 9, 6]